// POST /api/auth/register — port of Backend/app/auth/routes.py:64-90 (register).
//
// Explicit route: shadows the Phase 25 catch-all proxy for /api/auth/register.
// Prisma-direct (single-writer registration flow — no Python hop).
//
// Behavior parity (AUTH-01, D-07):
//   * creates a users row: bcrypt hash (rounds 12 via password.ts), scopes
//     ["basic"], uuid auto-generated by the DB
//   * triggers a verification-code email (emails.ts generateAndSendVerification)
//   * returns UserOut shape { uuid, email, scopes, is_verified, is_master }
//   * NEVER auto-logs-in — NO cookies, NO tokens minted (D-07 parity):
//     a bare register grants nothing; the visitor then logs in and verifies
//
// Rate limit: register 5/min per route+IP (backend routes.py:65 parity).
// Error contract: Phase 25 D-12 shape { error, code, retryable }.

import { randomUUID } from "node:crypto";

import { NextResponse, type NextRequest } from "next/server";

import { prisma } from "@/lib/prisma";
import { generateAndSendVerification } from "@/lib/auth/emails";
import { ip } from "@/lib/auth/ip";
import { AuthError } from "@/lib/auth/jwt";
import { hashPassword } from "@/lib/auth/password";
import { RATE_LIMITS, rateLimit } from "@/lib/auth/rate-limit";

// Minimal inline validation — UserCreate parity (schemas.py:5-7):
//   email: EmailStr (underscored basic format check; the SPA sends the raw value)
//   password: 6..72
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

export async function POST(req: NextRequest) {
  try {
    // Body parse — malformed JSON → 400 D-12 (FastAPI ValidationError parity).
    let body: unknown;
    try {
      body = await req.json();
    } catch {
      return NextResponse.json(
        { error: "JSON inválido", code: "BAD_REQUEST", retryable: false },
        { status: 400 },
      );
    }

    if (typeof body !== "object" || body === null) {
      return NextResponse.json(
        { error: "JSON inválido", code: "BAD_REQUEST", retryable: false },
        { status: 400 },
      );
    }

    const { email, password } = body as { email?: unknown; password?: unknown };

    if (typeof email !== "string" || !EMAIL_RE.test(email)) {
      return NextResponse.json(
        { error: "E-mail inválido", code: "BAD_REQUEST", retryable: false },
        { status: 400 },
      );
    }
    if (typeof password !== "string") {
      return NextResponse.json(
        { error: "Senha deve ter 6 caracteres", code: "BAD_REQUEST", retryable: false },
        { status: 400 },
      );
    }

    // Rate limit BEFORE any expensive work — register 5/min (routes.py:65).
    const rl = rateLimit(`register:${ip(req)}`, RATE_LIMITS.register);
    if (!rl.ok) {
      return NextResponse.json(
        {
          error: "Muitas tentativas. Tente novamente em instantes.",
          code: "RATE_LIMITED",
          retryable: true,
        },
        {
          status: 429,
          headers: { "Retry-After": String(rl.retryAfterSeconds) },
        },
      );
    }

    // Duplicate email — parity routes.py:70. Normalize to lowercase so that
    // login (token) and forgot-password lookups (which lowercase the submitted
    // email) can always find the account regardless of the original case.
    const normalizedEmail = email.toLowerCase();
    // Case-INSENSITIVE duplicate check: the email column is a case-sensitive
    // unique index (schema.prisma), so a bare exact findUnique would let a
    // lowercase twin coexist with a legacy mixed-case row ("User@Example.com"
    // pre-fix + "user@example.com" now) — and the insensitive lookups in
    // token/forgot-password would then resolve indeterminately, shadowing one
    // owner. Closing the twin at the write boundary keeps those lookups
    // deterministic (exact-first, insensitive-fallback). findFirst required:
    // findUnique only accepts scalar equality on the unique email field.
    const existing = await prisma.user.findFirst({
      where: { email: { equals: normalizedEmail, mode: "insensitive" } },
    });
    if (existing) {
      return NextResponse.json(
        { error: "Email já cadastrado", code: "BAD_REQUEST", retryable: false },
        { status: 400 },
      );
    }

    // Password length guards — routes.py:72-74 (min 6) + schemas.py:7 max 72
    // (UserCreate max_length=72 — bcrypt 72-byte limit; decodified into an
    // explicit message per plan). Max check is BYTE-based (TextEncoder) to
    // match password.ts hashPassword guard and reset-password/route.ts:81.
    if (password.length < 6) {
      return NextResponse.json(
        { error: "Senha deve ter 6 caracteres", code: "BAD_REQUEST", retryable: false },
        { status: 400 },
      );
    }
    if (new TextEncoder().encode(password).length > 72) {
      return NextResponse.json(
        {
          error: "Senha deve ter no máximo 72 caracteres",
          code: "BAD_REQUEST",
          retryable: false,
        },
        { status: 400 },
      );
    }

    const hashed = await hashPassword(password);
    // uuid generated server-side — backend models.py:14-20 default
    // `str(uuid.uuid4())` parity (the Prisma schema has no DB-side default).
    const user = await prisma.user.create({
      data: { uuid: randomUUID(), email: normalizedEmail, password: hashed, scopes: ["basic"] },
    });

    // Verification email trigger. On deliverability failure the user row already
    // exists (backend parity routes.py:84-88) — return 500, code remains settable
    // via /resend-verification.
    try {
      await generateAndSendVerification(user.id);
    } catch (err) {
      console.error("[register] falha ao enviar e-mail de verificação:", err);
      return NextResponse.json(
        {
          error: "Erro ao enviar e-mail",
          code: "EMAIL_SEND_FAILED",
          retryable: true,
        },
        { status: 500 },
      );
    }

    // UserOut shape (schemas.py:10-15) — NO cookies, NO tokens (D-07 no auto-login).
    return NextResponse.json(
      {
        uuid: user.uuid,
        email: user.email,
        scopes: ["basic"],
        is_verified: false,
        is_master: false,
      },
      {
        status: 200,
        headers: { "Cache-Control": "no-store" },
      },
    );
  } catch (err) {
    if (err instanceof AuthError) {
      return NextResponse.json(
        { error: err.message, code: err.code, retryable: err.retryable },
        { status: err.status },
      );
    }
    // Unknown server error — D-12 500 shape.
    return NextResponse.json(
      { error: "Erro interno", code: "INTERNAL_ERROR", retryable: true },
      { status: 500 },
    );
  }
}
